name: Maven Package

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          server-id: ossrh

      - name: Set new version
        run: |
          mvn versions:set -DnewVersion=${GITHUB_REF#refs/tags/}
          mvn versions:commit

      - name: Publish
        run: mvn clean deploy -P release -DskipTests  -s $GITHUB_WORKSPACE/.m2/settings.xml

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}

